version: "3.9"
services:
  app:
    build: .
    ports:
      - "${HOST_PORT}:3000" # Map host port (env var) to container port 3000
    volumes:
      - "${PWD}/src:/app/src"
      - "${PWD}/public:/app/public"
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start
    logging:
      driver: json-file
      options:
        max-size: "20m"
        max-file: "5"  