services:
  main:
    image: t1
    ports:
      - "${PORT}:3000"
    environment:
      - HOST=0.0.0.0
      - WDS_SOCKET_HOST=0.0.0.0
      - WDS_SOCKET_PORT=${PORT}
    volumes:
      - ${SRC_PATH}:/app
      - node_modules:/app/node_modules:ro
      - ${PWD}/package.json:/app/package.json:ro
      - ${SESS_PATH}/full_tests:/root/tst/full_tests:ro
      - ${SESS_PATH}/local_tests:/root/tst/local_tests
    command: ["sh", "-c", "sh /ssh_entrypoint.sh; sh /app/start_cmd.sh"]

  vscode:
    volumes:
      - ${SESS_PATH}/local_tests:/app/itk-academy/__test__
        
volumes:
  node_modules:
